name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build, Lint & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Lint
        run: |
          if npm run | grep -qE "^[[:space:]]*lint"; then
            npm run lint
          else
            echo "Skipping lint?no script found."
          fi

      - name: Unit tests
        run: |
          if npm run | grep -qE "^[[:space:]]*test"; then
            npm test -- --ci --runInBand
          else
            echo "Skipping tests?no script found."
          fi

      - name: Build
        id: build
        run: |
          if npm run | grep -qE "^[[:space:]]*build"; then
            npm run build
          else
            echo "Skipping build?no script found."
          fi

      - name: Upload artifact
        if: |
          success() &&
          (steps.build.outcome == 'success' || steps.build.outcome == 'skipped')
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-node${{ matrix.node }}
          path: |
            dist
            build
            extension/build
          if-no-files-found: ignore